Problem: tx log attribtue value not parsable by some client
tharsis/ethermint pull request #615
Opened 2021-10-03 00:11 UTC by yihuang

Closes: #614

Solution:
- encode the value to json string rather than bytes

Closes: #XXX

## Description

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

2021-10-03 00:20 UTC, yihuang commented on rpc/ethereum/backend/utils.go
> +	"json"
```suggestion
	"encoding/json"
```

2021-10-03 00:20 UTC, yihuang commented on x/evm/keeper/msg_server.go
> +	"json"
```suggestion
	"encoding/json"
```

2021-10-03 02:35 UTC, Piyushblog reviewed
It is good but somewhere it is wrong

2021-10-03 13:37 UTC, thomas-nguy commented
related to this issue https://github.com/informalsystems/tendermint-rs/issues/1003

2021-10-03 13:37 UTC, thomas-nguy approved these changes

2021-10-04 08:20 UTC, fedekunze requested changes
LGTM. Only left 1 comment. Let's also add a changelog entry 👍

2021-10-04 08:20 UTC, fedekunze commented on rpc/ethereum/backend/utils.go
> +				panic(err)
ah I wouldn't panic here, let's return an error

2021-10-04 09:21 UTC, thomas-nguy commented on rpc/ethereum/backend/utils.go
> +			if err := json.Unmarshal(attr.Value, &log); err != nil {
codec is unused

2021-10-05 09:31 UTC, fedekunze commented on rpc/ethereum/backend/utils.go
> +				panic(err)
bump

2021-10-05 09:32 UTC, fedekunze commented
please add a changelog entry too so that we can track the bug-fixes

2021-10-05 10:17 UTC, fedekunze approved these changes

2021-10-05 10:26 UTC, merged