No tx cli to build evm transaction
tharsis/ethermint pull request #712
Opened 2021-11-01 09:39 UTC by yihuang

Closes #709

## Description

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

2021-11-01 10:27 UTC, fedekunze requested changes
Looks good. Thanks, @yihuang. See comments below

2021-11-01 10:27 UTC, fedekunze commented on x/evm/client/cli/tx.go
> +
```suggestion
```

2021-11-01 10:27 UTC, fedekunze commented on x/evm/client/cli/tx.go
> +func CmdRaw() *cobra.Command {
```suggestion
// NewRawTxCmd command build cosmos transaction from raw ethereum transaction
func NewRawTxCmd() *cobra.Command {
```

2021-11-01 10:27 UTC, fedekunze commented on x/evm/client/cli/tx.go
> +				return err
```suggestion
				return errors.Wrap(err, "failed to decode ethereum tx hex bytes")
```

2021-11-01 10:27 UTC, fedekunze commented on x/evm/client/cli/tx.go
> +					_, _ = fmt.Fprintf(os.Stderr, "%s\n", "cancelled transaction")
```suggestion
					_, _ = fmt.Fprintf(os.Stderr, "%s\n", "canceled transaction")
```

2021-11-01 10:27 UTC, fedekunze commented on x/evm/types/msg.go
> +func (msg *MsgEthereumTx) UnmarshalBinary(b []byte) error {
we should add a unit test for this

2021-11-01 10:27 UTC, fedekunze commented on x/evm/types/msg.go
> +	return nil
```suggestion
	return msg.FromEthereumTx(tx)
```

2021-11-01 10:27 UTC, fedekunze commented on x/evm/client/cli/tx.go
> +			}
```suggestion
			if err := msg.UnmarshalBinary(data); err != nil {
				return err
			}
			
			if err := msg.ValidateBasic(); err != nil {
				return err
			}
```

2021-11-01 10:27 UTC, fedekunze commented on x/evm/types/utils.go
> +func BuildRawTransaction(builder authtx.ExtensionOptionsTxBuilder, msg *MsgEthereumTx, evmDenom string) (signing.Tx, error) {
ditto unit test

2021-11-01 10:27 UTC, fedekunze commented on x/evm/client/cli/tx.go
> +			data, err := hexutil.Decode(args[1])
```suggestion
			data, err := hexutil.Decode(args[0])
```

2021-11-02 03:37 UTC, yihuang commented on x/evm/types/utils.go
> +func BuildRawTransaction(builder authtx.ExtensionOptionsTxBuilder, msg *MsgEthereumTx, evmDenom string) (signing.Tx, error) {
done, also renamed to `BuildTx` method.

2021-11-02 03:37 UTC, yihuang commented on x/evm/types/msg.go
> +func (msg *MsgEthereumTx) UnmarshalBinary(b []byte) error {
done

2021-11-02 10:33 UTC, fedekunze approved these changes
ACK. Pending Changelog entry and lint fixes

2021-11-02 10:37 UTC, yihuang commented
> ACK. Pending Changelog entry and lint fixes

done

2021-11-02 11:20 UTC, merged