Problem: missing json rpc of eth_feeHistory #685
tharsis/ethermint pull request #734
Opened 2021-11-09 14:25 UTC by leejw51crypto

Solution: add feehistory api

2021-11-12 05:32 UTC, leejw51crypto commented
will add unit test
and will limit count

because it's heavy task, can be used maliciously

2021-11-12 08:20 UTC, fedekunze commented
@leejw51crypto let me know if you need support with this PR, I'd like to add it for the next release

2021-11-12 08:40 UTC, leejw51crypto commented
ok

2021-11-15 23:41 UTC, leejw51crypto commented
add unit test
rebased

2021-11-16 06:50 UTC, leejw51crypto commented
fix golangci-lint

2021-11-16 10:00 UTC, fedekunze requested changes
thanks @leejw51crypto, please add more comments and clean up the logic based on the comments. Also if you could add a changelog entry

2021-11-16 10:00 UTC, fedekunze commented on rpc/ethereum/backend/feebackend.go
> +			return nil, processerr
```suggestion
			return nil, err
```

2021-11-17 01:09 UTC, leejw51crypto commented on rpc/ethereum/backend/feebackend.go
> +			return nil, processerr
ok, i'll modify

2021-11-17 01:10 UTC, leejw51crypto commented
i'll modify

2021-11-17 01:11 UTC, leejw51crypto commented on rpc/ethereum/backend/feebackend.go
> +	}
yes, i'll return error if gaslimit is 0

2021-11-17 06:36 UTC, leejw51crypto commented on rpc/ethereum/backend/feebackend.go
> +		}
just err!=nil is enough

2021-11-17 06:53 UTC, leejw51crypto commented on rpc/ethereum/backend/feebackend.go
> +	}
ok

2021-11-17 08:51 UTC, leejw51crypto commented
default history cap is 100 to prevent ddos attack,
can configured with app.toml
```
# FeeHistoryCap sets the global cap for total number of blocks that can be fetched
feehistory-cap = 100
```

2021-11-17 11:44 UTC, fedekunze reviewed
LGTM minor comments

2021-11-17 11:44 UTC, fedekunze commented on rpc/ethereum/backend/backend.go
> +func (e *EVMBackend) RPCFeeHistgoryCap() int32 {
```suggestion
func (e *EVMBackend) RPCFeeHistoryCap() int32 {
```
```suggestion
func (e *EVMBackend) RPCFeeHistgoryCap() int32 {
```

2021-11-17 11:44 UTC, fedekunze commented on rpc/ethereum/backend/feebackend.go
> +	}
```suggestion

	if gasLimitUint64 <= 0 {
		return fmt.Errorf("gasLimit of block height %d should be bigger than 0 , current gaslimit %d", blockHeight, gasLimitUint64)
	}
	
	gasUsedRatio := gasusedfloat / float64(gasLimitUint64)
```
```suggestion
	var gasUsedRatio float64
	if gasLimitUint64 > 0 {
		gasUsedRatio = gasusedfloat / float64(gasLimitUint64)
	} else {
		return fmt.Errorf("gasLimit of block height %d should be bigger than 0 , current gaslimit %d", blockHeight, gasLimitUint64)
	}
```

2021-11-17 11:44 UTC, fedekunze commented on rpc/ethereum/backend/feebackend.go
> +			break
I don't understand the purpose of this break here, are we only supporting 1 `MsgEthereumTx` message?

2021-11-17 11:44 UTC, fedekunze commented on rpc/ethereum/backend/feebackend.go
> +	rewardPercentiles []float64) /* percentiles to fetch reward */ (*rpctypes.FeeHistoryResult, error) {
```suggestion
func (e *EVMBackend) FeeHistory(
	userBlockCount rpc.DecimalOrHex, // number blocks to fetch, maximum is 100
	lastBlock rpc.BlockNumber, // the block to start search , to oldest
	rewardPercentiles []float64, // percentiles to fetch reward
)  (*rpctypes.FeeHistoryResult, error) {
```

2021-11-17 11:44 UTC, fedekunze commented on rpc/ethereum/backend/feebackend.go
> +
```suggestion
```

2021-11-17 11:44 UTC, fedekunze commented on rpc/ethereum/types/types.go
> +	GasUsedRatio float64    /* the ratio of gas used to gas limit for each block */
```suggestion
	BaseFee      *big.Int   // base fee  for each block
	Reward       []*big.Int // each element of the array will have the tip provided to miners for the percentile given
	GasUsedRatio float64    // the ratio of gas used to the gas limit for each block
```

2021-11-17 11:46 UTC, fedekunze approved these changes

2021-11-17 11:58 UTC, merged