consistent baseFee check logic
tharsis/ethermint pull request #855
Opened 2021-12-23 07:56 UTC by yihuang

Closes: #755

```
if not london_hardfork {
    # reject DynamicFeeTx
    # no `baseFeePerGas` field in block response
    # baseFee = nil
} else {
    # allow DynamicFeeTx
    # add `baseFeePerGas` field in block response
    if feemarketParams.NoBaseFee or height < feemarketParams.EnableHeight {
        # baseFee = 0
    } else {
        # init baseFee to initBaseFee and adjust in later blocks
    }
}
```

Closes: #XXX

## Description

______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

2021-12-23 15:38 UTC, fedekunze requested changes
suggested changes LGTM. I'd add more test cases for the new behavior and also add a changelog entry.

2021-12-23 15:38 UTC, fedekunze commented on x/evm/keeper/keeper.go
> +		baseFee = new(big.Int)
just to make it explicit
```suggestion
		baseFee = big.NewInt(0)
```

2021-12-23 15:38 UTC, fedekunze commented on app/ante/eth.go
> +		}
can we add a test for this case?

2021-12-23 15:38 UTC, fedekunze commented on app/ante/eth.go
> +			}
can we add test cases here?

2021-12-23 15:38 UTC, fedekunze commented on x/evm/keeper/keeper.go
> +func (k Keeper) BaseFee(ctx sdk.Context, ethCfg *params.ChainConfig) *big.Int {
can we add a unit test for this function?

2021-12-25 18:16 UTC, fedekunze approved these changes
ACK, can you add a changelog entry?

2021-12-25 18:16 UTC, fedekunze commented on app/ante/utils_test.go
> +			}
```suggestion
			err := feemarketGenesis.Validate()
			suite.Require().NoError(err)
```

2021-12-27 07:24 UTC, yihuang commented
> ACK, can you add a changelog entry?

done, also added unit test for `EvmKeeper.BaseFee`.

2021-12-28 07:59 UTC, merged