upgrade geth to v1.10.15
tharsis/ethermint pull request #935
Opened 2022-02-11 13:57 UTC by crypto-facs

Closes: #XXX

## Description

Upgrade Geth version to the latest stable release [v1.10.15](https://github.com/ethereum/go-ethereum/releases/tag/v1.10.15). More detail explanation of changes can be found here https://github.com/ethereum/go-ethereum/milestone/127?closed=1

Major changes on the tracers were done on v.10.14 which required some changes on our side, specially around js tracer which requires a previous initiation of the tracer as a passive import on `app.go`. 

______

For contributor use:

- [x] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

2022-02-11 14:27 UTC, fedekunze commented on Makefile
> +-BUILD_FLAGS := -tags "$(build_tags)" -ldflags '$(ldflags)'
why the change?

2022-02-11 14:28 UTC, fedekunze commented on x/evm/keeper/grpc_query.go
>  	switch tracer := tracer.(type) {
are we adding the native tracer (go)?

2022-02-11 14:28 UTC, fedekunze commented on x/evm/keeper/state_transition.go
> -		NoRecursion: false, // TODO: consider disabling recursion though params
not required anymore?

2022-02-11 15:18 UTC, fedekunze approved these changes
ACK pending changelog

2022-02-11 15:21 UTC, crypto-facs commented on Makefile
> +-BUILD_FLAGS := -tags "$(build_tags)" -ldflags '$(ldflags)'
a mistake 🙏

2022-02-11 15:22 UTC, crypto-facs commented on x/evm/types/tracer.go
>  	switch tracer {
native tracer falls under `tracers.Tracer` interface

2022-02-12 08:50 UTC, loredanacirstea approved these changes
LGTM - I did similar changes in my branch when trying to work with the latest development version of geth v.1.10.15
Caveat: I do not yet understand why some of the PR checks fail.

2022-02-12 15:02 UTC, hanchon commented on CHANGELOG.md
> +* (evm) [tharsis#935](https://github.com/tharsis/ethermint/pull/935) Bumb Go-ethereum version to [`v1.0.15`](https://github.com/ethereum/go-ethereum/releases/tag/v1.10.15)
```suggestion
* (evm) [tharsis#935](https://github.com/tharsis/ethermint/pull/935) Bumb Go-ethereum version to [`v1.10.15`](https://github.com/ethereum/go-ethereum/releases/tag/v1.10.15)
```
typo

2022-02-12 23:58 UTC, crypto-facs commented on CHANGELOG.md
> +* (evm) [tharsis#935](https://github.com/tharsis/ethermint/pull/935) Bumb Go-ethereum version to [`v1.0.15`](https://github.com/ethereum/go-ethereum/releases/tag/v1.10.15)
Great catch

2022-02-14 23:00 UTC, fedekunze requested changes
Minor comment only

2022-02-14 23:00 UTC, fedekunze commented on x/evm/types/chain_config.go
> +		MergeForkBlock:          nil,
this should be `getBlockValue`

2022-02-14 23:06 UTC, fedekunze approved these changes

2022-02-14 23:08 UTC, merged