fix: simulations don't generate EVM transactions
tharsis/ethermint pull request #996
Opened 2022-03-16 07:36 UTC by Muggle-Du

Closes: #658 

## Description

Now the evm module doesn't generate random evm txs for the application simulation.

Generally speaking, we should implement the method `WeightedOperations` for x/evm module by generating random EthereumTx messages so that we can apply random evm txs to the module when we call the `SimulateFromSeed`. When implementing `WeightedOperations`, we can retrieve previous random `EthAccount` from auth module's `AccoutKeeper`. 

By default, auth module will only generate genesis base accounts and vesting accounts in simulation. But we can pass in custom `RandomGenesisAccounts ` when initializing the application's `SimulationManager` so that we can generate genesis `EthAccount` and other account types for simulation.
```go
app.sm = module.NewSimulationManager(
		// auth.NewAppModule(appCodec, app.AccountKeeper, authsims.RandomGenesisAccounts),
		auth.NewAppModule(appCodec, app.AccountKeeper, RandomGenesisAccounts),
...
```
______

For contributor use:

- [ ] Targeted PR against correct branch (see [CONTRIBUTING.md](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#pr-targeting))
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [ ] Wrote unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/master/CONTRIBUTING.md#testing)
- [ ] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [ ] Added  relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [ ] Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ] Re-reviewed `Files changed` in the Github PR explorer

______

For admin use:

- [ ] Added appropriate labels to PR (ex. `WIP`, `R4R`, `docs`, etc)
- [ ] Reviewers assigned
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" ([coding standards](https://github.com/tendermint/coding/blob/master/README.md#merging-a-pr))

2022-03-30 07:09 UTC, fedekunze reviewed
First pass

2022-03-30 07:09 UTC, fedekunze commented on app/test_helpers.go
> +		prv := secp256k1.GenPrivKeyFromSecret(privkeySeed)
do we not have this func on the `ethsecp256k1` package?

2022-03-30 07:09 UTC, fedekunze commented on app/test_helpers.go
> +		ethPrv.UnmarshalAmino(prv.Bytes())
why amino?

2022-03-30 07:09 UTC, fedekunze commented on x/evm/simulation/genesis.go
> +		params = types.NewParams(sdk.DefaultBondDenom, true, true, types.DefaultChainConfig(), 1344, 1884, 2200, 2929, 3198, 3529)
why the change?

2022-03-30 07:09 UTC, fedekunze commented on x/evm/simulation/operations.go
> +	WeightMsgEthCreateContract = 100
imo weight should be lower here

2022-03-30 07:09 UTC, fedekunze commented on x/evm/simulation/operations.go
> +		// ),
uncomment?

2022-03-30 07:09 UTC, fedekunze commented on x/evm/simulation/operations.go
> +}
why public struct with unexported fields?

2022-03-30 07:09 UTC, fedekunze commented on x/evm/simulation/operations.go
> +		amount = new(big.Int).Set(spendable)
we should return here

2022-03-30 07:09 UTC, fedekunze commented on x/evm/simulation/operations.go
> +		amount = simAmount.BigInt()
return

2022-03-30 07:09 UTC, fedekunze commented on x/evm/simulation/operations.go
> +	}
```suggestion
	if err != nil {
		return simtypes.NoOpMsg(types.ModuleName, types.TypeMsgEthereumTx, "failed to deliver tx"), nil, err
	}

```

2022-03-30 07:09 UTC, fedekunze commented on x/evm/simulation/operations.go
> +	ethTx, err := CreateRandomValidEthTx(ctx, from, nil, nil, (*hexutil.Bytes)(data))
```suggestion
	ethTx, err := CreateRandomValidEthTx(ctx, from, nil, nil, data)
```

2022-03-30 12:40 UTC, fedekunze requested changes
@Muggle-Du can you fix the linter and build errors?

2022-03-31 03:26 UTC, Muggle-Du commented
> @Muggle-Du can you fix the linter and build errors?

Sure, fixed

2022-04-07 13:36 UTC, fedekunze reviewed
Left comments to enable the other simulations

2022-04-07 13:36 UTC, fedekunze commented on app/test_helpers.go
> +// The default auth module's RandomGenesisAccounts implementation creates only base accounts and vestings accounts
```suggestion
// RandomGenesisAccounts is used by the auth module to create random genesis accounts in simulation when a genesis.json is not specified.
// In contrast, the default auth module's RandomGenesisAccounts implementation creates only base accounts and vestings accounts. 
```

2022-04-07 13:36 UTC, fedekunze commented on app/test_helpers.go
> +// Create random accounts with ethsecp256k1.PrivKey
```suggestion
// RandomAccounts creates random accounts with an ethsecp256k1 private key
```

2022-04-07 13:36 UTC, fedekunze commented on x/evm/module.go
>  // WeightedOperations returns the all the evm module operations with their respective weights.
we need to add the functions above too

- `RandomizedParams`
- `RegisterStoreDecoder`
- `ProposalContents`

2022-04-07 13:36 UTC, fedekunze commented on x/evm/simulation/genesis.go
> +		params = types.NewParams(sdk.DefaultBondDenom, true, true, types.DefaultChainConfig(), 1344, 1884, 2200, 2929, 3198, 3529)
undo change

2022-04-07 13:36 UTC, fedekunze commented on x/evm/simulation/operations.go
> +}
I think we can remove this and use the one from the SDK config (`sdk.GetConfig`)

2022-04-12 12:57 UTC, fedekunze commented
@Muggle-Du are you planning to fix the remaining comments? cc @crypto-facs

2022-04-13 05:52 UTC, fedekunze requested changes
Thanks for the changes. Added more comments. Currently missing:

- `Features` changelog entry
- tests for the new `Random...` functions
- tests for the simulation package functions, specially decoder
- update Github actions to run the simulation
- define `RandomizedParams` in  `x/evm/module.go`
- update godoc comments

2022-04-13 05:52 UTC, fedekunze commented on x/evm/module.go
>  // WeightedOperations returns the all the evm module operations with their respective weights.
`RandomizedParams` is still missing

2022-04-13 05:52 UTC, fedekunze commented on x/evm/simulation/operations.go
> +func GetSignedTx(ctx *simulateContext, txBuilder client.TxBuilder, msg *types.MsgEthereumTx, prv cryptotypes.PrivKey) (signedTx signing.Tx, err error) {
update godoc, it should always start with the name of the function. The current comment is also not very descriptive

2022-04-13 05:52 UTC, fedekunze commented on x/evm/simulation/operations.go
> +// Transferable amount is between the range [0, spendable), spendable = balance - gasFeeCap * GasLimit
update godoc

2022-04-13 05:52 UTC, fedekunze commented on x/evm/simulation/operations.go
> +		GasCap: config.DefaultGasCap,
why are we always using the default?

2022-04-13 05:52 UTC, fedekunze commented on x/evm/simulation/operations.go
> +// Estimate gas used by quering the keeper
update godoc comment

2022-04-13 05:52 UTC, fedekunze commented on x/evm/simulation/operations.go
> +	gasLimit := estimateGas + uint64(ctx.rand.Intn(int(sdktx.MaxGasWanted-estimateGas)))
can you explain the rationale for this random value?

2022-04-13 05:52 UTC, fedekunze commented on x/evm/simulation/operations.go
> +// Populate the ethereum tx with valid random values
update

2022-04-13 05:52 UTC, fedekunze commented on x/evm/simulation/operations.go
> +func SimulateEthTx(ctx *simulateContext, from, to *common.Address, amount *big.Int, data *hexutil.Bytes, prv cryptotypes.PrivKey, fops []simtypes.FutureOperation) (simtypes.OperationMsg, []simtypes.F
update comment and split lines

2022-04-13 05:52 UTC, fedekunze commented on x/evm/simulation/operations.go
> +func operationSimulateEthCallContract(k *keeper.Keeper, contractAddr, to *common.Address, amount *big.Int) simtypes.Operation {
this should mention that it's always calling an ERC20 contract

2022-04-13 05:52 UTC, fedekunze commented on x/evm/simulation/operations.go
> +// operationSimulateEthCallContract is the future operations of SimulateEthCreateContract to make sure valid contract call
update comment

2022-04-13 05:52 UTC, fedekunze commented on x/evm/simulation/operations.go
> +func SimulateEthSimpleTransfer(ak types.AccountKeeper, k *keeper.Keeper) simtypes.Operation {
update comment

2022-04-13 05:52 UTC, fedekunze commented on x/evm/simulation/operations.go
> +func WeightedOperations(
update comment

2022-04-13 05:52 UTC, fedekunze commented on x/evm/simulation/genesis.go
> +	params := types.NewParams(sdk.DefaultBondDenom, true, true, types.DefaultChainConfig())
```suggestion
	params := types.NewParams(types.DefaultEVMDenom, true, true, types.DefaultChainConfig())
```

2022-04-13 05:52 UTC, fedekunze commented on x/evm/simulation/genesis.go
> +		params = types.NewParams(sdk.DefaultBondDenom, true, true, types.DefaultChainConfig(), 1344, 1884, 2200, 2929, 3198, 3529)
```suggestion
		params = types.NewParams(types.DefaultEVMDenom, true, true, types.DefaultChainConfig(), 1344, 1884, 2200, 2929, 3198, 3529)
```

2022-04-13 05:52 UTC, fedekunze commented on x/evm/simulation/genesis.go
> +	sdk "github.com/cosmos/cosmos-sdk/types"
instead of using the params with the sdk.DefaultBondDenom, we should replace it through an `init` function

2022-04-14 13:05 UTC, fedekunze commented on x/evm/simulation/genesis.go
> +	sdk "github.com/cosmos/cosmos-sdk/types"
```suggestion
```

2022-04-19 07:01 UTC, fedekunze commented on x/evm/simulation/params.go
> +	}
we should add param changes for the other params too

2022-04-19 07:03 UTC, fedekunze commented on app/utils.go
> +		err = cdc.UnmarshalJSON(evmStateBz, evmState)
use MustUnmarshal

2022-04-19 07:03 UTC, fedekunze commented on app/utils.go
> +		err = cdc.UnmarshalJSON(stakingStateBz, stakingState)
ditto

2022-04-19 07:03 UTC, fedekunze commented on app/utils.go
> +		err := json.Unmarshal(appState, &rawState)
we should use the cdc JSON marshaler here

2022-04-19 07:03 UTC, fedekunze commented on app/utils.go
> +		appState, err = json.Marshal(rawState)
ditto JSON marshaler from codec

2022-04-19 09:44 UTC, fedekunze approved these changes

2022-04-19 09:44 UTC, fedekunze commented on x/evm/simulation/params.go
> +	}
Please add as a follow-up

2022-04-19 09:45 UTC, fedekunze commented on x/evm/simulation/operations.go
> +		GasCap: config.DefaultGasCap,
add as follow-up

2022-04-19 09:45 UTC, fedekunze commented on x/evm/simulation/operations.go
> +	gasLimit := estimateGas + uint64(ctx.rand.Intn(int(sdktx.MaxGasWanted-estimateGas)))
add comment in follow-up

2022-04-19 09:50 UTC, merged